### PR TITLE
Using skipper to maintain dmc.xml

### PR DESCRIPTION
**Pull request by basz**
I have confirmed the rewritten dmc.xml file work and generate the same sql

Not sure a proprietary tool like Skipper is appropriate in a OSS project but I use it and it works

### CODE REVIEW

**Comment by prolic** [comment]
Maybe you use skipper on your dev machine, but not commit skipper files to the repo? What do you think?

**Comment by basz** [comment]
i will get lost...

**Comment by prolic** [comment]
Put it in your directory and add to .git/config/exclude??

Am 25.02.2017 00:31 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by basz** [comment]
ok. squased you win ;-)

**Review by prolic — APPROVED** [review]

**Pull request merged**
