### PR TITLE
switch to use datetimetz fields 

### PR DESCRIPTION
**Pull request by basz**
#18

### CODE REVIEW

**Comment by prolic** [comment]
What about DoctrineExtensions\DBAL\Types\UTCDateTimeType ?

**Comment by basz** [comment]
That would introduce a dependency dont you think. I think you must register that type and use the utcdatetime type.

Since by default doctrine reads datetime in the default tz of php, wouldn't it be simpler to just write them in the php default tz too?

Strange that this problem hasn't been solved in a decent way...

**Comment by basz** [comment]
ok, not

```
Type::overrideType('datetime', UTCDateTimeType::class);
Type::overrideType('datetimetz', UTCDateTimeType::class);
```

then it would be an application concern, wouldn't you agree? The user implements UTCDateTimeType and knowingly overrides the doctrine provided DateTimeType.

**Comment by prolic** [comment]
Ok so manually switching timezones then.

Sascha-Oliver Prolic

2017-04-29 4:08 GMT+08:00 Bas Kamer <notifications@github.com>:

**Comment by basz** [comment]
I implemented this. Thx for the pointer, works great

**Pull request closed without merging**
